// KONTE 2022
CREATE TABLE Pakke (
    PID INTEGER AUTO_INCREMENT NOT NULL,
    LID INTEGER,
    EIER VARCHAR(50),
    VEKT DOUBLE PRECISION,
    VOLUM DOUBLE PRECISION,
    FOREIGN KEY (LID) REFERENCES Lager(LID),
    PRIMARY KEY (PID)
);

CREATE TABLE Lager (
    LID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    ADRESSE VARCHAR(50),
    PRIMARY KEY (LID)
);

INSERT INTO Lager (NAVN, ADRESSE) VALUES ( 'Hovedlager', 'Østre aker vei 203' );
INSERT INTO Lager (NAVN, ADRESSE) VALUES ( 'Ekeberg container', 'Ekebergveien 12' );

CREATE TABLE Bruker (
    BID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    PASSORD VARCHAR(255),
    PRIMARY KEY (BID)
);

