// KONTE 2022
CREATE TABLE IF NOT EXISTS Pakke (
    PID INTEGER AUTO_INCREMENT,
    LID INTEGER,
    EIER VARCHAR(50),
    VEKT DOUBLE PRECISION,
    VOLUM DOUBLE PRECISION,
    FOREIGN KEY (LID) REFERENCES Lager(LID),
    PRIMARY KEY (PID)
);

// Her skal egentlig ikke PID legges inn.
INSERT INTO Pakke (LID, EIER, VEKT, VOLUM) VALUES (1, 'Sander', 2, 8 );

CREATE TABLE IF NOT EXISTS Lager (
    LID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    ADRESSE VARCHAR(50),
    PRIMARY KEY (LID)
);

INSERT INTO Lager (NAVN, ADRESSE) VALUES ( 'Hovedlager', 'Eksamensveien 12' );

CREATE TABLE IF NOT EXISTS Bruker (
    BID INTEGER AUTO_INCREMENT NOT NULL,
    NAVN VARCHAR(50),
    PASSORD VARCHAR(255),
    PRIMARY KEY (BID)
);